import { useEffect, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom';
import apiClient from '../api';
import Layout from '../components/Layout';

const content = {
  ticketing: [['How to book tickets online?', 'Search a route, choose a train and ticket class, select passengers, then submit and confirm the order.'], ['What ID documents are accepted?', 'Foreign passengers can purchase real-name tickets with a valid passport or another supported identity document.'], ['What is real-name ticketing?', 'To ensure the safety and order of passenger transportation, railway operation company has implemented real-name ticketing.'], ['How many kinds of tickets are there?', 'Currently, both E-tickets and paper tickets are on sale.'], ['Where can I buy the ticket?', 'Please purchase train tickets from channels offered by railway operation company or its sales agency.']],
  refund: [['How to change or refund tickets?', 'Passengers can change or refund tickets through 12306.cn before departure, subject to the current railway service rules.'], ['What is endorsement?', 'Endorsement means changing the date, train number, seat type or destination of a ticket according to the applicable rules.'], ['What are the rules of ticket endorsement?', 'Please check the departure time and the available trains before confirming an endorsement.'], ['How is a refund calculated?', 'Refund fees depend on the time between the refund request and the scheduled departure.']],
  misc: [['How to check train status?', 'Search by train number or route to see current departure and arrival information.'], ['How to use 12306 mobile app?', 'Use the official mobile application to search routes, manage passengers and review orders.'], ['How can I contact support?', 'The Contact us entry provides service assistance for common booking questions.'], ['What documents are accepted?', 'A valid passport or other supported identity document is required for real-name travel.']],
} as const;

export default function GuidePage() { const params = new URLSearchParams(useLocation().search); const requested = (params.get('tab') || 'ticketing') as keyof typeof content; const [tab, setTab] = useState(requested in content ? requested : 'ticketing'); const [remote, setRemote] = useState<Record<string, string[][]>>({}); const question = params.get('q'); const target = useRef<HTMLElement>(null); useEffect(() => { apiClient.get('/search/guides').then(({ data }) => { const grouped: Record<string, string[][]> = {}; for (const item of data.guides || []) { const key = item.category === 'Ticketing' ? 'ticketing' : item.category === 'Endorsement and refund' ? 'refund' : 'misc'; (grouped[key] ||= []).push([item.question, item.detail]); } setRemote(grouped); }); }, []); useEffect(() => { setTab(requested in content ? requested : 'ticketing'); }, [requested]); useEffect(() => { if (!question) return; const timer = window.setTimeout(() => target.current?.scrollIntoView({ block: 'center' }), 100); return () => window.clearTimeout(timer); }, [question, tab, remote]); const entries = (remote[tab] || content[tab]) as string[][]; return <Layout><div className="guide-page"><div className="tabs guide-tabs">{(['ticketing', 'refund', 'misc'] as const).map(key => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}>{key === 'ticketing' ? 'Ticketing' : key === 'refund' ? 'Endorsement and refund' : 'Miscellaneous'}</button>)}</div><article className="guide-content">{entries.map(([heading, body], index) => <section id={`guide-question-${index + 1}`} data-question={heading} ref={question === heading ? target : undefined} key={heading}><h2>{index + 1}. {heading}</h2><p>{body}</p></section>)}</article></div></Layout>; }
